-- MortaLeague account system
-- Run this in Supabase SQL Editor AFTER creating a Supabase project.
-- Authentication is username-only at the UI level; the frontend maps usernames
-- to synthetic internal emails. Do NOT expose service_role keys in the site.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  message text not null check (char_length(message) between 5 and 2000),
  status text not null default 'Bekliyor',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.support_messages enable row level security;

create policy "profiles are readable by owner"
on public.profiles for select
using (auth.uid() = id);

create policy "profile owner can insert"
on public.profiles for insert
with check (auth.uid() = id);

create policy "profile owner can update"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "users can create their own support messages"
on public.support_messages for insert
with check (auth.uid() = user_id);

create policy "users can read their own support messages"
on public.support_messages for select
using (auth.uid() = user_id);

-- IMPORTANT:
-- Keep Supabase email confirmation disabled for this username-only setup,
-- otherwise users cannot confirm the synthetic email address.
